---

- hosts: ldapserver
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: yes
  vars:
   ansible_ssh_private_key_file: "/home/ubuntu/.ssh/my_aws"
  pre_tasks:
   - name: 'install python'
     raw: 'sudo apt-get -y install python'
  roles:
      - install-openldap
