---

- name: Get my public IP
  ipify_facts:
    timeout: 20
  delegate_to: localhost
  register: public_ip

- name: output
  debug: msg="{{ipify_public_ip}}"

- name: create ssh key
  openssh_keypair:
     path: "/home/ubuntu/.ssh/{{key_name}}"
     type: rsa
     size: 4096

- name: install boto3 python module for aws
  apt:
     pkg:
     - python-boto3
     - python-boto

- name: Provisioning EC2 instances
  block:

  - name: Upload public key to AWS
    ec2_key:
      name: "{{ key_name }}"
      key_material: "{{ lookup('file', '/home/ubuntu/.ssh/{{ key_name }}.pub') }}" # my key's location
      region: "{{ region }}"
      aws_access_key: "{{ec2_access_key}}" # i made global vars with my keys in ansible vault (more secure)
      aws_secret_key: "{{ec2_secret_key}}"

  - name: Create security group
    ec2_group:
      name: "{{ sec_group }}"
      description: "Sec group for app {{ id }}"
      region: "{{ region }}"
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      rules:
        - proto: tcp
          ports:
            - 22
            - 80
          cidr_ip: "{{ ipify_public_ip }}/32" # my ip
          rule_desc: allow inbound traffic from me on ssh and http port
    register: result_sec_group

  - name: Provision instance
    ec2:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      key_name: "{{ key_name }}"
      instance_tags:
        name: "{{id}}"
      group_id: "{{ result_sec_group.group_id }}"
      image: "{{ image }}"
      instance_type: t2.micro
      region: "{{ region }}"
      wait: true
      count: 1
    register: ec2

  - name: Add the newly created host so that we can further contact it
    add_host:
      name: "{{ item.public_ip }}"
      groups: ldapserver
    with_items: "{{ ec2.instances }}"


  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_ip }}"
      port: 22
      state: started
    with_items: "{{ ec2.instances }}"
